"""  Problem2:18-2-2020
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the
Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
lst = [1, 2]
for x in range(400000):
    c = lst[x] + lst[x + 1]
    if c >= 4000000:
        break
    lst.append(c)
print('sum', sum(list(filter(lambda c: c % 2 == 0, lst))))




# Problem3: Largest prime factor  10-3-2020
def Largest_prime_factor(number):
    s = []
    for x in range(2, number):
        if number % x == 0 and number / x != 1:
            s.append(x)
            new_number = int(number / x)
            number = new_number
    s.append(new_number)
    s.sort()
    print(f"The Prime Factor:{s}\nThe Largest Prime factor :{max(s)}")

####################################################################
# Problem 4: Largest palindrome product
####################################################################
# Problem 5:Smallest multiple
for smallest_num in range(1, 250000000):
    check_list = []
    for x in range(1, 11):
        if smallest_num % x == 0:
            check_list.append(x)
            check_list.sort()
            if check_list == [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:

                print("Smallest Number is : ", smallest_num)
                exit()
###################################################################
# Problem 6: Sum square difference
import numpy as np

fl = []
for x in range(1, 101):
    fl.append(x)
f_array = np.array(fl)
print("The difference is :", sum(f_array) ** 2 - sum(f_array ** 2))

###################################################################
# Problem 7:
for x in range(1, 10):
    s = []
    for y in range(3, 100):
        if y % x != 0:
            s.append(y)
    print(s)
    """


def check(num1):
    for x in range(2, 10):
        if num1 % x != 0:
            continue
        return num1


k = []
for y in range(3, 100, 2):
    s = [2]
    for x in range(2, 10):
        if y % x != 0:
          check(y)
